# Generated by Django 3.0.4 on 2020-04-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_timeentry_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.Project'),
        ),
    ]
